// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ToDoListManagement.Entity.Data;

#nullable disable

namespace ToDoListManagement.Entity.Migrations
{
    [DbContext(typeof(ToDoListDbContext))]
    [Migration("20250703062624_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ToDoListManagement.Entity.Models.ErrorLog", b =>
                {
                    b.Property<int>("ErrorLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ErrorLogId"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text");

                    b.HasKey("ErrorLogId");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("ToDoListManagement.Entity.Models.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PermissionId"));

                    b.Property<bool>("CanAddEdit")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanView")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PermissionName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("PermissionId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("RoleId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            PermissionId = 1,
                            CanAddEdit = true,
                            CanDelete = true,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 3, 6, 26, 24, 121, DateTimeKind.Utc).AddTicks(1579),
                            IsDeleted = false,
                            PermissionName = "Projects",
                            RoleId = 1
                        },
                        new
                        {
                            PermissionId = 2,
                            CanAddEdit = true,
                            CanDelete = true,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 3, 6, 26, 24, 121, DateTimeKind.Utc).AddTicks(1603),
                            IsDeleted = false,
                            PermissionName = "Employees",
                            RoleId = 1
                        },
                        new
                        {
                            PermissionId = 3,
                            CanAddEdit = true,
                            CanDelete = true,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 3, 6, 26, 24, 121, DateTimeKind.Utc).AddTicks(1622),
                            IsDeleted = false,
                            PermissionName = "Task Board",
                            RoleId = 1
                        },
                        new
                        {
                            PermissionId = 4,
                            CanAddEdit = true,
                            CanDelete = true,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 3, 6, 26, 24, 121, DateTimeKind.Utc).AddTicks(1640),
                            IsDeleted = false,
                            PermissionName = "Role And Permissions",
                            RoleId = 1
                        },
                        new
                        {
                            PermissionId = 5,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 3, 6, 26, 24, 121, DateTimeKind.Utc).AddTicks(1658),
                            IsDeleted = false,
                            PermissionName = "Projects",
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 6,
                            CanAddEdit = true,
                            CanDelete = true,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 3, 6, 26, 24, 121, DateTimeKind.Utc).AddTicks(1679),
                            IsDeleted = false,
                            PermissionName = "Employees",
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 7,
                            CanAddEdit = true,
                            CanDelete = true,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 3, 6, 26, 24, 121, DateTimeKind.Utc).AddTicks(1697),
                            IsDeleted = false,
                            PermissionName = "Task Board",
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 8,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = false,
                            CreatedAt = new DateTime(2025, 7, 3, 6, 26, 24, 121, DateTimeKind.Utc).AddTicks(1716),
                            IsDeleted = false,
                            PermissionName = "Role And Permissions",
                            RoleId = 2
                        },
                        new
                        {
                            PermissionId = 9,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 3, 6, 26, 24, 121, DateTimeKind.Utc).AddTicks(1735),
                            IsDeleted = false,
                            PermissionName = "Projects",
                            RoleId = 3
                        },
                        new
                        {
                            PermissionId = 10,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 3, 6, 26, 24, 121, DateTimeKind.Utc).AddTicks(1756),
                            IsDeleted = false,
                            PermissionName = "Employees",
                            RoleId = 3
                        },
                        new
                        {
                            PermissionId = 11,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 3, 6, 26, 24, 121, DateTimeKind.Utc).AddTicks(1776),
                            IsDeleted = false,
                            PermissionName = "Task Board",
                            RoleId = 3
                        },
                        new
                        {
                            PermissionId = 12,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = false,
                            CreatedAt = new DateTime(2025, 7, 3, 6, 26, 24, 121, DateTimeKind.Utc).AddTicks(1794),
                            IsDeleted = false,
                            PermissionName = "Role And Permissions",
                            RoleId = 3
                        },
                        new
                        {
                            PermissionId = 13,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 3, 6, 26, 24, 121, DateTimeKind.Utc).AddTicks(1811),
                            IsDeleted = false,
                            PermissionName = "Projects",
                            RoleId = 4
                        },
                        new
                        {
                            PermissionId = 14,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 3, 6, 26, 24, 121, DateTimeKind.Utc).AddTicks(1840),
                            IsDeleted = false,
                            PermissionName = "Employees",
                            RoleId = 4
                        },
                        new
                        {
                            PermissionId = 15,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = true,
                            CreatedAt = new DateTime(2025, 7, 3, 6, 26, 24, 121, DateTimeKind.Utc).AddTicks(1859),
                            IsDeleted = false,
                            PermissionName = "Task Board",
                            RoleId = 4
                        },
                        new
                        {
                            PermissionId = 16,
                            CanAddEdit = false,
                            CanDelete = false,
                            CanView = false,
                            CreatedAt = new DateTime(2025, 7, 3, 6, 26, 24, 121, DateTimeKind.Utc).AddTicks(1878),
                            IsDeleted = false,
                            PermissionName = "Role And Permissions",
                            RoleId = 4
                        });
                });

            modelBuilder.Entity("ToDoListManagement.Entity.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProjectId"));

                    b.Property<int?>("AssignedToProgramManager")
                        .HasColumnType("integer");

                    b.Property<int?>("AssignedToScrumMaster")
                        .HasColumnType("integer");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("ProjectName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ProjectId");

                    b.HasIndex("AssignedToProgramManager");

                    b.HasIndex("AssignedToScrumMaster");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ToDoListManagement.Entity.Models.ProjectUser", b =>
                {
                    b.Property<int>("ProjectUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProjectUserId"));

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ProjectUserId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectUsers");
                });

            modelBuilder.Entity("ToDoListManagement.Entity.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("RoleName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            CreatedAt = new DateTime(2025, 7, 3, 6, 26, 24, 121, DateTimeKind.Utc).AddTicks(1463),
                            IsDeleted = false,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            CreatedAt = new DateTime(2025, 7, 3, 6, 26, 24, 121, DateTimeKind.Utc).AddTicks(1510),
                            IsDeleted = false,
                            RoleName = "Program Manager"
                        },
                        new
                        {
                            RoleId = 3,
                            CreatedAt = new DateTime(2025, 7, 3, 6, 26, 24, 121, DateTimeKind.Utc).AddTicks(1533),
                            IsDeleted = false,
                            RoleName = "Member"
                        },
                        new
                        {
                            RoleId = 4,
                            CreatedAt = new DateTime(2025, 7, 3, 6, 26, 24, 121, DateTimeKind.Utc).AddTicks(1553),
                            IsDeleted = false,
                            RoleName = "ScrumMaster"
                        });
                });

            modelBuilder.Entity("ToDoListManagement.Entity.Models.Sprint", b =>
                {
                    b.Property<int>("SprintId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SprintId"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int>("ScrumMasterId")
                        .HasColumnType("integer");

                    b.Property<string>("SprintName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.HasKey("SprintId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("ScrumMasterId");

                    b.ToTable("Sprint");
                });

            modelBuilder.Entity("ToDoListManagement.Entity.Models.TaskAttachment", b =>
                {
                    b.Property<int>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AttachmentId"));

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsImage")
                        .HasColumnType("boolean");

                    b.Property<int?>("TaskId")
                        .HasColumnType("integer");

                    b.Property<int?>("UploadedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UploadedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AttachmentId");

                    b.HasIndex("DeletedBy");

                    b.HasIndex("TaskId");

                    b.HasIndex("UploadedBy");

                    b.ToTable("TaskAttachments");
                });

            modelBuilder.Entity("ToDoListManagement.Entity.Models.ToDoList", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TaskId"));

                    b.Property<int?>("AssignedTo")
                        .HasColumnType("integer");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Priority")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int?>("SprintId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("TaskId");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ProjectId");

                    b.HasIndex("SprintId");

                    b.ToTable("ToDoLists");
                });

            modelBuilder.Entity("ToDoListManagement.Entity.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "admin@outlook.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Admin",
                            PasswordHash = "$2a$11$YCiiJxUwumHUtegC05ahFej29UzVm/s1HRwPriPIuta4b.GWddWuW",
                            PhoneNumber = "9988556644",
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("ToDoListManagement.Entity.Models.Permission", b =>
                {
                    b.HasOne("ToDoListManagement.Entity.Models.User", "CreatedByNavigation")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("ToDoListManagement.Entity.Models.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToDoListManagement.Entity.Models.User", "UpdatedByNavigation")
                        .WithMany()
                        .HasForeignKey("UpdatedBy");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("Role");

                    b.Navigation("UpdatedByNavigation");
                });

            modelBuilder.Entity("ToDoListManagement.Entity.Models.Project", b =>
                {
                    b.HasOne("ToDoListManagement.Entity.Models.User", "AssignedPM")
                        .WithMany()
                        .HasForeignKey("AssignedToProgramManager");

                    b.HasOne("ToDoListManagement.Entity.Models.User", "ScrumMaster")
                        .WithMany()
                        .HasForeignKey("AssignedToScrumMaster");

                    b.HasOne("ToDoListManagement.Entity.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.Navigation("AssignedPM");

                    b.Navigation("ScrumMaster");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToDoListManagement.Entity.Models.ProjectUser", b =>
                {
                    b.HasOne("ToDoListManagement.Entity.Models.Project", "Project")
                        .WithMany("ProjectUsers")
                        .HasForeignKey("ProjectId");

                    b.HasOne("ToDoListManagement.Entity.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ToDoListManagement.Entity.Models.Sprint", b =>
                {
                    b.HasOne("ToDoListManagement.Entity.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ToDoListManagement.Entity.Models.User", "ScrumMaster")
                        .WithMany()
                        .HasForeignKey("ScrumMasterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("ScrumMaster");
                });

            modelBuilder.Entity("ToDoListManagement.Entity.Models.TaskAttachment", b =>
                {
                    b.HasOne("ToDoListManagement.Entity.Models.User", "DeletedByUser")
                        .WithMany()
                        .HasForeignKey("DeletedBy");

                    b.HasOne("ToDoListManagement.Entity.Models.ToDoList", "ToDoList")
                        .WithMany()
                        .HasForeignKey("TaskId");

                    b.HasOne("ToDoListManagement.Entity.Models.User", "UploadedByUser")
                        .WithMany()
                        .HasForeignKey("UploadedBy");

                    b.Navigation("DeletedByUser");

                    b.Navigation("ToDoList");

                    b.Navigation("UploadedByUser");
                });

            modelBuilder.Entity("ToDoListManagement.Entity.Models.ToDoList", b =>
                {
                    b.HasOne("ToDoListManagement.Entity.Models.User", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedTo");

                    b.HasOne("ToDoListManagement.Entity.Models.User", "CreatedUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("ToDoListManagement.Entity.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.HasOne("ToDoListManagement.Entity.Models.Sprint", "Sprint")
                        .WithMany()
                        .HasForeignKey("SprintId");

                    b.Navigation("AssignedUser");

                    b.Navigation("CreatedUser");

                    b.Navigation("Project");

                    b.Navigation("Sprint");
                });

            modelBuilder.Entity("ToDoListManagement.Entity.Models.User", b =>
                {
                    b.HasOne("ToDoListManagement.Entity.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ToDoListManagement.Entity.Models.Project", b =>
                {
                    b.Navigation("ProjectUsers");
                });

            modelBuilder.Entity("ToDoListManagement.Entity.Models.Role", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
